### ISSUE TITLE
Unable to deploy ARM template for ACR with replication in complete mode with Az CLI version greater than 2.0.72 | HomeReplicationCannotBeDeleted

### ISSUE THREAD

**Issue by AdamSharif-MSFT** [Azure/acr#294]
**Describe the bug**
When deploying an ARM template to create an ACR with replication in COMPLETE mode with the latest version of the Azure CLI, the deployment takes a very long time and eventually fails with error **HomeReplicationCannotBeDeleted**.
This only affects COMPLETE mode deployments, and the previous workaround described here is no longer working: https://github.com/Azure/azure-quickstart-templates/issues/5485

**To Reproduce**
1. Create an ARM template for ACR with multiple replications included, or export a template from the portal
2. Deploy in COMPLETE mode with Azure CLI version greater than 2.0.72, or Cloud Shell:
`az group deployment create -g _<rgName>_ --mode Complete --template-file _<templateFile>_ --parameters _<parametersFile>_ –debug`
3. Watch the deployment, after an extended time it will fail and you will see the error

**Expected behavior**
Expecting to see a successful COMPLETE mode deployment, without failure.

**Screenshots**

**Any relevant environment information**
 - OS: Windows/Linux
 - Azure CLI/PowerShell/SDK version: Az CLI 2.0.75, Cloud Shell
 - Datetime (UTC) when the issue occurred: Happening now - reproducible issue

**Additional context**

Example template:

```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "registryname": {
            "defaultValue": "mytestacr",
            "type": "String"
        }
    },
    "variables": {},
    "resources": [
        {
            "type": "Microsoft.ContainerRegistry/registries",
            "apiVersion": "2017-10-01",
            "name": "[parameters('registryname')]",
            "location": "westeurope",
            "sku": {
                "name": "Premium",
                "tier": "Premium"
            },
            "properties": {
                "adminUserEnabled": true
            }
        },

       {
            "condition": false,
            "type": "Microsoft.ContainerRegistry/registries/replications",
            "apiVersion": "2017-10-01",
            "name": "[concat(parameters('registryname'), '/westeurope')]",
            "location": "westeurope",
            "dependsOn": [
                "[resourceId('Microsoft.ContainerRegistry/registries', parameters('registryname'))]"
            ],
            "properties": {
                "provisioningState": "Succeeded",
                "status": {
                    "displayStatus": "Ready",
                    "timestamp": "2019-10-17T12:16:48.7920032Z"
                }
            }
        },
        {
            "type": "Microsoft.ContainerRegistry/registries/replications",
            "apiVersion": "2017-10-01",
            "name": "[concat(parameters('registryname'), '/eastus')]",
            "location": "eastus",
            "dependsOn": [
                "[resourceId('Microsoft.ContainerRegistry/registries', parameters('registryname'))]"
            ]
        }
    ]
}
```

If any information is a concern to post here, you can create a [support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) or send an email to acrsup@microsoft.com.

**Comment by ankurkhemani** [comment]
@AdamSharif-MSFT The fix has been deployed and should work now.

**Comment by AdamSharif-MSFT** [comment]
Hi @ankurkhemani ,

Thank you for the update - I tried to create an ACR just now using latest version (2.0.81) of the Azure CLI, with the template mentioned in the original post, but I'm having the same issue:

![image](https://user-images.githubusercontent.com/40294242/74234183-2c5fd380-4cc4-11ea-9878-b3b2bfe94448.png)

Do the API versions in the template need to be changed, and if so which values should be used?

Correlation ID: b3ec05ee-9d03-4cc6-8008-76b940197561

Latest error:

"HomeReplicationCannotBeDeleted\",\"message\":\"Cannot delete replication in home region WESTEUROPE as there are one or more active replications. For more information, please visit https://aka.ms/acr/geo-replication#delete-a-replica\"

**Comment by ankurkhemani** [comment]
As discussed, you need to order the replications in such a way that home replication gets created after one of the replication resource. This can be achieved by modifying `dependsOn` for westeurope (home) replica: 

```
"dependsOn": [
    "[resourceId('Microsoft.ContainerRegistry/registries/replications', parameters('registries_byaksacr_name'), 'eastus')]"
]
```

**Comment by ankurkhemani** [comment]
Closing as this issue has been fixed.

**Comment by wronda** [comment]
@ankurkhemani Adding the `dependsOn` as you've stated doesn't solve the issue in our case. Are you sure this was done with `complete` mode. Any other pointers you could give? This is still an issue for us.

**Comment by ankurkhemani** [comment]
@wronda Can you please also remove the `"condition": false` from home replication. It was a workaround that was needed earlier. After this fix, we don't need it anymore.
